type LiteralUnion<T extends string> = T | (string & Record<never, never>);

export const knownIconNames = [
  "ArrowRight",
  "ArrowUp",
  "ArrowUpRight",
  "Award",
  "Banknote",
  "Briefcase",
  "Calculator",
  "Check",
  "CheckSquare",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "ChevronsRight",
  "ClipboardList",
  "Clock",
  "Diamond",
  "DollarSign",
  "FileCheck",
  "FileSpreadsheet",
  "FileText",
  "Globe",
  "Headset",
  "Headphones",
  "Languages",
  "Laptop",
  "Link",
  "Mail",
  "MailOpen",
  "MapPin",
  "MessageCircle",
  "Minus",
  "Monitor",
  "MoveLeft",
  "MoveRight",
  "Phone",
  "Play",
  "Plus",
  "Quote",
  "Receipt",
  "Search",
  "Send",
  "Settings",
  "ShieldCheck",
  "Star",
  "ThumbsUp",
  "TriangleRight",
  "Trophy",
  "Users",
  "UsersRound",
  "X",
] as const;

export type KnownIconName = (typeof knownIconNames)[number];
export type IconName = LiteralUnion<KnownIconName>;
